[package]
name = "hash_sign_01"
version = "1.0.0"

[addresses]
HashSign="0x6f2a11a75c9def967c7dcfdf2e61d7b989d9c423bf646ade5b8fe3e7edee27af"
aptos_framework = "0x1"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
